### ISSUE TITLE
sửa lại repo adduser vì khi tạo user không cần  ảnh (ráng tối nay xong luôn nha luôn nha 😆 )

### ISSUE THREAD

**Issue by phu1110** [Junn1o/motelapi#19]

**Comment by phu1110** [comment]
hoặc có thể để user thành một cái logo mặc định nào đó khi tạo mà muốn thay đổi thì user tự update lại

**Comment by Junn1o** [comment]
sao ko cho là nếu không có ảnh nào được chọn thì sẽ chọn mặc định, còn có ảnh thì upload ảnh? Được ko
